services:
  app:
    container_name: docteur-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    depends_on:
      - db
    networks:
      - docteur-network

  db:
    container_name: docteur-db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432" # Exposed on 5434 to avoid conflict with local postgres if running
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docteur-network

networks:
  docteur-network:
    driver: bridge

volumes:
  postgres_data:
